// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOM289adZ7NG_8WZvzwMTOmoiWjZyQTas',
    appId: '1:970550088606:web:1fbf4313fcfc042d227c8f',
    messagingSenderId: '970550088606',
    projectId: 'cineday-aa004',
    authDomain: 'cineday-aa004.firebaseapp.com',
    storageBucket: 'cineday-aa004.firebasestorage.app',
    measurementId: 'G-J43DVZCR1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NJnMk5y29dOt5IJLYlJq7pp-m1vtNdg',
    appId: '1:970550088606:android:88bb60cb25b6e2ec227c8f',
    messagingSenderId: '970550088606',
    projectId: 'cineday-aa004',
    storageBucket: 'cineday-aa004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbGjfzvhbohW7fGIToPbZ3otHYj9ULBzU',
    appId: '1:970550088606:ios:a928a5bf3c6ddfd9227c8f',
    messagingSenderId: '970550088606',
    projectId: 'cineday-aa004',
    storageBucket: 'cineday-aa004.firebasestorage.app',
    iosBundleId: 'com.example.cineDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbGjfzvhbohW7fGIToPbZ3otHYj9ULBzU',
    appId: '1:970550088606:ios:a928a5bf3c6ddfd9227c8f',
    messagingSenderId: '970550088606',
    projectId: 'cineday-aa004',
    storageBucket: 'cineday-aa004.firebasestorage.app',
    iosBundleId: 'com.example.cineDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOM289adZ7NG_8WZvzwMTOmoiWjZyQTas',
    appId: '1:970550088606:web:0e1a7099681cd17a227c8f',
    messagingSenderId: '970550088606',
    projectId: 'cineday-aa004',
    authDomain: 'cineday-aa004.firebaseapp.com',
    storageBucket: 'cineday-aa004.firebasestorage.app',
    measurementId: 'G-GDEDM3WPEF',
  );
}
